matrix:
  include:
    # GCC 7
  - os: linux
    dist: trusty
    sudo: required
    addons: &gcc7
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - xorg-dev 
        - libglu1-mesa-dev
        - libopenal1
        artifacts:
          paths: Build/Release/
    language: cpp
    compiler: gcc
    env:
    - COMPILER=g++-7
    - GSL_CXX_STANDARD=17
    before_install:
    - echo "deb http://ppa.launchpad.net/keithw/glfw3/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list.d/fillwave_ext.list
    - echo "deb-src http://ppa.launchpad.net/keithw/glfw3/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list.d/fillwave_ext.list
    - sudo apt-get -qq update
    - sudo apt-get install --allow-unauthenticated libglfw3 libglfw3-dev
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  # Clang 6.0
  - os: linux
    dist: trusty
    sudo: required
    addons: &clang60
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
        - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
        - clang-6.0
        - libc++-dev
        - xorg-dev 
        - libglu1-mesa-dev
        - libopenal1
    language: cpp
    compiler: clang
    env:
    - COMPILER=clang++-6.0
    - GSL_CXX_STANDARD=17
    before_install:
    - echo "deb http://ppa.launchpad.net/keithw/glfw3/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list.d/fillwave_ext.list
    - echo "deb-src http://ppa.launchpad.net/keithw/glfw3/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list.d/fillwave_ext.list
    - sudo apt-get -qq update
    - sudo apt-get install --allow-unauthenticated libglfw3 libglfw3-dev
    - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-6.0 1000
  # XCode 9.1
  - os: osx
    osx_image: xcode9.1
    sudo: required
    language: cpp
    compiler: clang
    env:
    - COMPILER=clang++
    - GSL_CXX_STANDARD=17
    before_install:
    - brew install cmake || brew upgrade cmake

script:
- cd $TRAVIS_BUILD_DIR
- git submodule update --init --recursive
- mkdir Build
- cd Build
- |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
    else
      cmake .. -G "Xcode" -DCMAKE_BUILD_TYPE=Release
    fi
- ls
- |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      make all
    else
      xcodebuild -target Flounder -configuration Release
    fi
- cd ../
